import { dictionaries, type Locale, type TranslationKey } from '../../shared/i18n/dictionaries';

const keys = {
  advancedDesign: 'publicPageBuilder.advancedDesign', simpleEditor: 'publicPageBuilder.simpleEditor', advancedEditor: 'publicPageBuilder.advancedEditor',
  designEditorMode: 'publicPageBuilder.designEditorMode', typography: 'publicPageBuilder.typography', buttons: 'publicPageBuilder.buttons',
  customValues: 'publicPageBuilder.customValues', fromPageTheme: 'publicPageBuilder.fromPageTheme', resetGroup: 'publicPageBuilder.resetGroup',
  palettePreserves: 'publicPageBuilder.palettePreserves', sectionDefaults: 'publicPageBuilder.sectionDefaults',
  customButtonDesign: 'publicPageBuilder.customButtonDesign', buttonInheritance: 'publicPageBuilder.buttonInheritance', resetButtonDesign: 'publicPageBuilder.resetButtonDesign',
  animation: 'publicPageBuilder.animation', pulse: 'publicPageBuilder.pulse', lift: 'publicPageBuilder.lift', softShadow: 'publicPageBuilder.softShadow',
  reducedMotionHint: 'publicPageBuilder.reducedMotionHint', openInNewTab: 'publicPageBuilder.openInNewTab',
  scheduleEnabled: 'publicPageBuilder.scheduleEnabled', scheduleFrom: 'publicPageBuilder.scheduleFrom', scheduleUntil: 'publicPageBuilder.scheduleUntil',
  scheduleTimezone: 'publicPageBuilder.scheduleTimezone', scheduleBoundaryHint: 'publicPageBuilder.scheduleBoundaryHint', scheduleWeekdays: 'publicPageBuilder.scheduleWeekdays',
  scheduleInvalidDates: 'publicPageBuilder.scheduleInvalidDates', scheduleNoDays: 'publicPageBuilder.scheduleNoDays', scheduleAmbiguous: 'publicPageBuilder.scheduleAmbiguous', scheduleNonexistent: 'publicPageBuilder.scheduleNonexistent',
  scheduleActive: 'publicPageBuilder.scheduleActive', scheduleInactive: 'publicPageBuilder.scheduleInactive',
  monday: 'publicPageBuilder.monday', tuesday: 'publicPageBuilder.tuesday', wednesday: 'publicPageBuilder.wednesday', thursday: 'publicPageBuilder.thursday', friday: 'publicPageBuilder.friday', saturday: 'publicPageBuilder.saturday', sunday: 'publicPageBuilder.sunday',
  blockArchive: 'publicPageBuilder.blockArchive', archiveBlock: 'publicPageBuilder.archiveBlock', blockArchiveHint: 'publicPageBuilder.blockArchiveHint',
  blockArchiveEmpty: 'publicPageBuilder.blockArchiveEmpty', blockArchiveEmptyHint: 'publicPageBuilder.blockArchiveEmptyHint', sourceSectionRemoved: 'publicPageBuilder.sourceSectionRemoved',
  blockRestoreHint: 'publicPageBuilder.blockRestoreHint', blockRestored: 'publicPageBuilder.blockRestored', blockRestoreConflict: 'publicPageBuilder.blockRestoreConflict',
  unsaved: 'publicPageBuilder.unsaved',
  leaveWarning: 'publicPageBuilder.leaveWarning',
  stay: 'publicPageBuilder.stay',
  discardAndLeave: 'publicPageBuilder.discardAndLeave',
  saveAndLeave: 'publicPageBuilder.saveAndLeave',
  publishMissingTitle: 'publicPageBuilder.publishMissingTitle',
  publishMissingDescription: 'publicPageBuilder.publishMissingDescription',
  publishMissingBlock: 'publicPageBuilder.publishMissingBlock',
  publishInvalidBlock: 'publicPageBuilder.publishInvalidBlock',
  publishInvalidLink: 'publicPageBuilder.publishInvalidLink',
  publishInvalidMedia: 'publicPageBuilder.publishInvalidMedia',
  publishMissingAlt: 'publicPageBuilder.publishMissingAlt',
  publishMissingLabel: 'publicPageBuilder.publishMissingLabel',
  publishInvalidDocument: 'publicPageBuilder.publishInvalidDocument',
  pages: 'publicPageBuilder.pages', editorWorkspaceTitle: 'publicPageBuilder.editorWorkspaceTitle', pagesSubtitle: 'publicPageBuilder.pagesSubtitle',
  implementedTemplates: 'publicPageBuilder.implementedTemplates', templatePreviewHint: 'publicPageBuilder.templatePreviewHint',
  create: 'publicPageBuilder.create', empty: 'publicPageBuilder.empty',
  loading: 'publicPageBuilder.loading', retry: 'publicPageBuilder.retry', edit: 'publicPageBuilder.edit',
  duplicate: 'publicPageBuilder.duplicate', archive: 'publicPageBuilder.archive', restore: 'publicPageBuilder.restore', draft: 'publicPageBuilder.draft',
  published: 'publicPageBuilder.published', archived: 'publicPageBuilder.archived', save: 'publicPageBuilder.save',
  saving: 'publicPageBuilder.saving', saved: 'publicPageBuilder.saved', saveError: 'publicPageBuilder.saveError',
  publish: 'publicPageBuilder.publish', undo: 'publicPageBuilder.undo', redo: 'publicPageBuilder.redo',
  preview: 'publicPageBuilder.preview', open: 'publicPageBuilder.open', copyLink: 'publicPageBuilder.copyLink',
  mobileNavigation: 'publicPageBuilder.mobileNavigation',
  linkCopied: 'publicPageBuilder.linkCopied', addBlock: 'publicPageBuilder.addBlock',
  createNewSection: 'publicPageBuilder.createNewSection',
  page: 'publicPageBuilder.page', section: 'publicPageBuilder.section', block: 'publicPageBuilder.block',
  title: 'publicPageBuilder.title', description: 'publicPageBuilder.description', slug: 'publicPageBuilder.slug',
  visible: 'publicPageBuilder.visible', remove: 'publicPageBuilder.remove', moveUp: 'publicPageBuilder.moveUp',
  moveDown: 'publicPageBuilder.moveDown', name: 'publicPageBuilder.name', theme: 'publicPageBuilder.theme',
  reorderKeyboardHint: 'publicPageBuilder.reorderKeyboardHint', sectionReorderLabel: 'publicPageBuilder.sectionReorderLabel',
  blockReorderLabel: 'publicPageBuilder.blockReorderLabel', sectionMovedAnnouncement: 'publicPageBuilder.sectionMovedAnnouncement',
  blockMovedAnnouncement: 'publicPageBuilder.blockMovedAnnouncement', reorderAtStart: 'publicPageBuilder.reorderAtStart',
  reorderAtEnd: 'publicPageBuilder.reorderAtEnd',
  background: 'publicPageBuilder.background', textColor: 'publicPageBuilder.textColor',
  deviceMobile: 'publicPageBuilder.deviceMobile', deviceTablet: 'publicPageBuilder.deviceTablet',
  deviceDesktop: 'publicPageBuilder.deviceDesktop',
  noSelection: 'publicPageBuilder.noSelection', invalidSlug: 'publicPageBuilder.invalidSlug',
  slugChecking: 'publicPageBuilder.slugChecking', slugAvailable: 'publicPageBuilder.slugAvailable',
  slugUnavailable: 'publicPageBuilder.slugUnavailable', slugCheckError: 'publicPageBuilder.slugCheckError',
  publishedSlugChangeWarning: 'publicPageBuilder.publishedSlugChangeWarning',
  validation: 'publicPageBuilder.validation', notFound: 'publicPageBuilder.notFound',
  unavailable: 'publicPageBuilder.unavailable',
  template: 'publicPageBuilder.template', revisionConflict: 'publicPageBuilder.revisionConflict', slugConflict: 'publicPageBuilder.slugConflict',
  templatePreview: 'publicPageBuilder.templatePreview',
  reloadLatest: 'publicPageBuilder.reloadLatest',
  restoreSlugConflict: 'publicPageBuilder.restoreSlugConflict', restoreQuotaExceeded: 'publicPageBuilder.restoreQuotaExceeded',
  restoreRevisionConflict: 'publicPageBuilder.restoreRevisionConflict', restorePageState: 'publicPageBuilder.restorePageState',
  restoreError: 'publicPageBuilder.restoreError',
  addItem: 'publicPageBuilder.addItem',
  deleteConfirm: 'publicPageBuilder.deleteConfirm',
  uploadImage: 'publicPageBuilder.uploadImage', replaceImage: 'publicPageBuilder.replaceImage',
  imageAlt: 'publicPageBuilder.imageAlt', invalidImageType: 'publicPageBuilder.invalidImageType',
  imageTooLarge: 'publicPageBuilder.imageTooLarge', imageUploadError: 'publicPageBuilder.imageUploadError',
  displayName: 'publicPageBuilder.displayName', profileDescription: 'publicPageBuilder.profileDescription',
  logo: 'publicPageBuilder.logo', avatar: 'publicPageBuilder.avatar', avatarPosition: 'publicPageBuilder.avatarPosition',
  avatarPositionHint: 'publicPageBuilder.avatarPositionHint', centerImage: 'publicPageBuilder.centerImage', blockBackground: 'publicPageBuilder.blockBackground',
  pageBackground: 'publicPageBuilder.pageBackground', overlay: 'publicPageBuilder.overlay', imageFit: 'publicPageBuilder.imageFit',
  imageFitCover: 'publicPageBuilder.imageFitCover', imageFitContain: 'publicPageBuilder.imageFitContain',
  focalPoint: 'publicPageBuilder.focalPoint', font: 'publicPageBuilder.font', pageColor: 'publicPageBuilder.pageColor',
  backgroundPreset: 'publicPageBuilder.backgroundPreset',
  cancel: 'publicPageBuilder.cancel', configureBlock: 'publicPageBuilder.configureBlock',
  back: 'publicPageBuilder.back', close: 'publicPageBuilder.close', searchPlatforms: 'publicPageBuilder.searchPlatforms',
  pageSettings: 'publicPageBuilder.pageSettings', hide: 'publicPageBuilder.hide', show: 'publicPageBuilder.show',
  design: 'publicPageBuilder.design', colorPalettes: 'publicPageBuilder.colorPalettes', fonts: 'publicPageBuilder.fonts',
  fontPreview: 'publicPageBuilder.fontPreview',
  rounding: 'publicPageBuilder.rounding', rounded: 'publicPageBuilder.rounded', pill: 'publicPageBuilder.pill', leaf: 'publicPageBuilder.leaf', square: 'publicPageBuilder.square',
  linkStyles: 'publicPageBuilder.linkStyles', linkStyle: 'publicPageBuilder.linkStyle', backgroundImage: 'publicPageBuilder.backgroundImage',
  deleteBlockConfirm: 'publicPageBuilder.deleteBlockConfirm',
  deleteSectionConfirm: 'publicPageBuilder.deleteSectionConfirm', blockEditorLabel: 'publicPageBuilder.blockEditorLabel',
  mediaCleanupError: 'publicPageBuilder.mediaCleanupError',
  blockTypeLinks: 'publicPageBuilder.blockTypeLinks',
  blockTypeAvatar: 'publicPageBuilder.blockTypeAvatar', blockTypeButton: 'publicPageBuilder.blockTypeButton',
  blockTypeText: 'publicPageBuilder.blockTypeText', blockTypeImage: 'publicPageBuilder.blockTypeImage',
  blockTypeGallery: 'publicPageBuilder.blockTypeGallery', blockTypeServices: 'publicPageBuilder.blockTypeServices',
  blockTypeContacts: 'publicPageBuilder.blockTypeContacts', blockTypeMap: 'publicPageBuilder.blockTypeMap',
  blockTypeDivider: 'publicPageBuilder.blockTypeDivider', blockTypeFaq: 'publicPageBuilder.blockTypeFaq',
  items: 'publicPageBuilder.items', removeItem: 'publicPageBuilder.removeItem', addPlatform: 'publicPageBuilder.addPlatform',
  fieldTitle: 'publicPageBuilder.fieldTitle', fieldHeadline: 'publicPageBuilder.fieldHeadline', fieldSubtitle: 'publicPageBuilder.fieldSubtitle',
  fieldBody: 'publicPageBuilder.fieldBody', fieldDescription: 'publicPageBuilder.fieldDescription',
  fieldLabel: 'publicPageBuilder.fieldLabel', fieldUrl: 'publicPageBuilder.fieldUrl',
  fieldAddress: 'publicPageBuilder.fieldAddress', fieldPrice: 'publicPageBuilder.fieldPrice',
  fieldPlatform: 'publicPageBuilder.fieldPlatform', fieldValue: 'publicPageBuilder.fieldValue',
  fieldAction: 'publicPageBuilder.fieldAction', fieldPhone: 'publicPageBuilder.fieldPhone', fieldEmail: 'publicPageBuilder.fieldEmail',
  actionUrl: 'publicPageBuilder.actionUrl', actionPhone: 'publicPageBuilder.actionPhone',
  actionEmail: 'publicPageBuilder.actionEmail', actionMessenger: 'publicPageBuilder.actionMessenger',
  messagingApps: 'publicPageBuilder.messagingApps', socialNetworks: 'publicPageBuilder.socialNetworks',
  platformFacebookMessenger: 'publicPageBuilder.platformFacebookMessenger', platformVk: 'publicPageBuilder.platformVk',
  platformInstagram: 'publicPageBuilder.platformInstagram', platformTelegram: 'publicPageBuilder.platformTelegram',
  platformWhatsapp: 'publicPageBuilder.platformWhatsapp', platformViber: 'publicPageBuilder.platformViber',
  platformFacebook: 'publicPageBuilder.platformFacebook', platformThreads: 'publicPageBuilder.platformThreads', platformTiktok: 'publicPageBuilder.platformTiktok',
  tabContent: 'publicPageBuilder.tabContent', tabDesign: 'publicPageBuilder.tabDesign', tabSettings: 'publicPageBuilder.tabSettings', tabSection: 'publicPageBuilder.tabSection',
  fieldLayout: 'publicPageBuilder.fieldLayout', avatarLayoutCentered: 'publicPageBuilder.avatarLayoutCentered',
  avatarLayoutCoverCentered: 'publicPageBuilder.avatarLayoutCoverCentered', avatarLayoutCoverLeft: 'publicPageBuilder.avatarLayoutCoverLeft',
  avatarLayoutImageCover: 'publicPageBuilder.avatarLayoutImageCover', avatarSize: 'publicPageBuilder.avatarSize', cover: 'publicPageBuilder.cover',
  avatarLayoutImageLeft: 'publicPageBuilder.avatarLayoutImageLeft', avatarLayoutImageRight: 'publicPageBuilder.avatarLayoutImageRight',
  avatarLayoutCompact: 'publicPageBuilder.avatarLayoutCompact', paddingTop: 'publicPageBuilder.paddingTop',
  paddingBottom: 'publicPageBuilder.paddingBottom', horizontalMargin: 'publicPageBuilder.horizontalMargin',
  borderRadius: 'publicPageBuilder.borderRadius', borderWidth: 'publicPageBuilder.borderWidth', borderColor: 'publicPageBuilder.borderColor',
  drag: 'publicPageBuilder.drag', resizeSection: 'publicPageBuilder.resizeSection', dropBlock: 'publicPageBuilder.dropBlock', dropSection: 'publicPageBuilder.dropSection',
  clearSelection: 'publicPageBuilder.clearSelection', sectionOff: 'publicPageBuilder.sectionOff', newSection: 'publicPageBuilder.newSection',
  sectionsFromDesign: 'publicPageBuilder.sectionsFromDesign', primarySection: 'publicPageBuilder.primarySection', secondarySection: 'publicPageBuilder.secondarySection',
  none: 'publicPageBuilder.none', buttonIcon: 'publicPageBuilder.buttonIcon', buttonIconLink: 'publicPageBuilder.buttonIconLink',
  buttonIconPhone: 'publicPageBuilder.buttonIconPhone', buttonIconEmail: 'publicPageBuilder.buttonIconEmail', buttonIconMessage: 'publicPageBuilder.buttonIconMessage',
  buttonColor: 'publicPageBuilder.buttonColor', buttonTextColor: 'publicPageBuilder.buttonTextColor',
  shadow: 'publicPageBuilder.shadow', mobileVisible: 'publicPageBuilder.mobileVisible', sectionWidth: 'publicPageBuilder.sectionWidth',
  widthFull: 'publicPageBuilder.widthFull', widthContained: 'publicPageBuilder.widthContained',
  sectionBackground: 'publicPageBuilder.sectionBackground',
  headingStyle: 'publicPageBuilder.headingStyle', bodyStyle: 'publicPageBuilder.bodyStyle', linksStyle: 'publicPageBuilder.linksStyle',
  fontFamily: 'publicPageBuilder.fontFamily', fontSize: 'publicPageBuilder.fontSize', fontWeight: 'publicPageBuilder.fontWeight', fontStyle: 'publicPageBuilder.fontStyle',
  normal: 'publicPageBuilder.normal', italic: 'publicPageBuilder.italic', inherit: 'publicPageBuilder.inherit',
  titleStyle: 'publicPageBuilder.titleStyle', subtitleStyle: 'publicPageBuilder.subtitleStyle', backgroundOpacity: 'publicPageBuilder.backgroundOpacity',
  image: 'publicPageBuilder.image', addImage: 'publicPageBuilder.addImage',
  general: 'publicPageBuilder.general', pixels: 'publicPageBuilder.pixels', removeSection: 'publicPageBuilder.removeSection', enterText: 'publicPageBuilder.enterText',
  bold: 'publicPageBuilder.bold', underline: 'publicPageBuilder.underline', strike: 'publicPageBuilder.strike',
  alignLeft: 'publicPageBuilder.alignLeft', alignCenter: 'publicPageBuilder.alignCenter', alignRight: 'publicPageBuilder.alignRight', alignJustify: 'publicPageBuilder.alignJustify',
  textSizeSmall: 'publicPageBuilder.textSizeSmall', textSizeMedium: 'publicPageBuilder.textSizeMedium', textSizeLarge: 'publicPageBuilder.textSizeLarge',
  textSizeH1: 'publicPageBuilder.textSizeH1', textSizeH2: 'publicPageBuilder.textSizeH2', textSizeH3: 'publicPageBuilder.textSizeH3',
  chooseServices: 'publicPageBuilder.chooseServices', selectedServices: 'publicPageBuilder.selectedServices',
  addService: 'publicPageBuilder.addService', editService: 'publicPageBuilder.editService', refreshServices: 'publicPageBuilder.refreshServices',
  servicesLoading: 'publicPageBuilder.servicesLoading', servicesLoadError: 'publicPageBuilder.servicesLoadError',
  servicesNoneSelected: 'publicPageBuilder.servicesNoneSelected', servicesUnavailable: 'publicPageBuilder.servicesUnavailable',
  servicesCatalogEmpty: 'publicPageBuilder.servicesCatalogEmpty',
  servicesSelectionTitle: 'publicPageBuilder.servicesSelectionTitle', servicesSelectionLimit: 'publicPageBuilder.servicesSelectionLimit',
  confirmSelection: 'publicPageBuilder.confirmSelection', servicesAutoplay: 'publicPageBuilder.servicesAutoplay',
  servicesAutoplaySeconds: 'publicPageBuilder.servicesAutoplaySeconds', showBookingButton: 'publicPageBuilder.showBookingButton',
  serviceBook: 'publicPageBuilder.serviceBook', serviceMinutes: 'publicPageBuilder.serviceMinutes',
  serviceFirstSessionFree: 'publicPageBuilder.serviceFirstSessionFree', carouselSlide: 'publicPageBuilder.carouselSlide',
  serviceSlidePosition: 'publicPageBuilder.serviceSlidePosition', carouselNavigation: 'publicPageBuilder.carouselNavigation',
  goToServiceSlide: 'publicPageBuilder.goToServiceSlide', carouselPlay: 'publicPageBuilder.carouselPlay', carouselPause: 'publicPageBuilder.carouselPause',
} as const satisfies Record<string, TranslationKey>;

export type PublicPageUiKey = keyof typeof keys;

export function publicPageText(locale: Locale, key: PublicPageUiKey): string {
  const dictionaryKey = keys[key].slice('publicPageBuilder.'.length) as keyof typeof dictionaries.en.publicPageBuilder;
  return dictionaries[locale].publicPageBuilder[dictionaryKey];
}
