import { dictionaries, type Locale, type TranslationKey } from '../../shared/i18n/dictionaries';

const keys = {
  pages: 'publicPageBuilder.pages', create: 'publicPageBuilder.create', empty: 'publicPageBuilder.empty',
  loading: 'publicPageBuilder.loading', retry: 'publicPageBuilder.retry', edit: 'publicPageBuilder.edit',
  duplicate: 'publicPageBuilder.duplicate', archive: 'publicPageBuilder.archive', draft: 'publicPageBuilder.draft',
  published: 'publicPageBuilder.published', archived: 'publicPageBuilder.archived', save: 'publicPageBuilder.save',
  saving: 'publicPageBuilder.saving', saved: 'publicPageBuilder.saved', saveError: 'publicPageBuilder.saveError',
  publish: 'publicPageBuilder.publish', undo: 'publicPageBuilder.undo', redo: 'publicPageBuilder.redo',
  preview: 'publicPageBuilder.preview', open: 'publicPageBuilder.open', copyLink: 'publicPageBuilder.copyLink',
  linkCopied: 'publicPageBuilder.linkCopied', sections: 'publicPageBuilder.sections', blocks: 'publicPageBuilder.blocks',
  addSection: 'publicPageBuilder.addSection', addBlock: 'publicPageBuilder.addBlock', inspector: 'publicPageBuilder.inspector',
  createNewSection: 'publicPageBuilder.createNewSection',
  page: 'publicPageBuilder.page', section: 'publicPageBuilder.section', block: 'publicPageBuilder.block',
  title: 'publicPageBuilder.title', description: 'publicPageBuilder.description', slug: 'publicPageBuilder.slug',
  visible: 'publicPageBuilder.visible', remove: 'publicPageBuilder.remove', moveUp: 'publicPageBuilder.moveUp',
  moveDown: 'publicPageBuilder.moveDown', name: 'publicPageBuilder.name', theme: 'publicPageBuilder.theme',
  background: 'publicPageBuilder.background', textColor: 'publicPageBuilder.textColor',
  deviceMobile: 'publicPageBuilder.deviceMobile', deviceTablet: 'publicPageBuilder.deviceTablet',
  deviceDesktop: 'publicPageBuilder.deviceDesktop',
  noSelection: 'publicPageBuilder.noSelection', invalidSlug: 'publicPageBuilder.invalidSlug',
  validation: 'publicPageBuilder.validation', notFound: 'publicPageBuilder.notFound',
  unavailable: 'publicPageBuilder.unavailable',
  template: 'publicPageBuilder.template', revisionConflict: 'publicPageBuilder.revisionConflict',
  templatePreview: 'publicPageBuilder.templatePreview',
  reloadLatest: 'publicPageBuilder.reloadLatest',
  addItem: 'publicPageBuilder.addItem',
  deleteConfirm: 'publicPageBuilder.deleteConfirm',
  uploadImage: 'publicPageBuilder.uploadImage', replaceImage: 'publicPageBuilder.replaceImage',
  imageAlt: 'publicPageBuilder.imageAlt', invalidImageType: 'publicPageBuilder.invalidImageType',
  imageTooLarge: 'publicPageBuilder.imageTooLarge', imageUploadError: 'publicPageBuilder.imageUploadError',
  displayName: 'publicPageBuilder.displayName', profileDescription: 'publicPageBuilder.profileDescription',
  logo: 'publicPageBuilder.logo', avatar: 'publicPageBuilder.avatar', blockBackground: 'publicPageBuilder.blockBackground',
  pageBackground: 'publicPageBuilder.pageBackground', overlay: 'publicPageBuilder.overlay', imageFit: 'publicPageBuilder.imageFit',
  imageFitCover: 'publicPageBuilder.imageFitCover', imageFitContain: 'publicPageBuilder.imageFitContain',
  focalPoint: 'publicPageBuilder.focalPoint', font: 'publicPageBuilder.font', pageColor: 'publicPageBuilder.pageColor',
  backgroundPreset: 'publicPageBuilder.backgroundPreset',
  cancel: 'publicPageBuilder.cancel', configureBlock: 'publicPageBuilder.configureBlock',
  back: 'publicPageBuilder.back', close: 'publicPageBuilder.close', searchPlatforms: 'publicPageBuilder.searchPlatforms',
  pageSettings: 'publicPageBuilder.pageSettings', hide: 'publicPageBuilder.hide', show: 'publicPageBuilder.show',
  design: 'publicPageBuilder.design', colorPalettes: 'publicPageBuilder.colorPalettes', fonts: 'publicPageBuilder.fonts',
  fontPreview: 'publicPageBuilder.fontPreview',
  rounding: 'publicPageBuilder.rounding', rounded: 'publicPageBuilder.rounded', pill: 'publicPageBuilder.pill', leaf: 'publicPageBuilder.leaf', square: 'publicPageBuilder.square',
  linkStyles: 'publicPageBuilder.linkStyles', linkStyle: 'publicPageBuilder.linkStyle', backgroundImage: 'publicPageBuilder.backgroundImage',
  deleteBlockConfirm: 'publicPageBuilder.deleteBlockConfirm',
  deleteSectionConfirm: 'publicPageBuilder.deleteSectionConfirm', blockEditorLabel: 'publicPageBuilder.blockEditorLabel',
  mediaCleanupError: 'publicPageBuilder.mediaCleanupError',
  blockTypeHero: 'publicPageBuilder.blockTypeHero', blockTypeLinks: 'publicPageBuilder.blockTypeLinks',
  blockTypeAvatar: 'publicPageBuilder.blockTypeAvatar', blockTypeButton: 'publicPageBuilder.blockTypeButton',
  blockTypeText: 'publicPageBuilder.blockTypeText', blockTypeImage: 'publicPageBuilder.blockTypeImage',
  blockTypeGallery: 'publicPageBuilder.blockTypeGallery', blockTypeServices: 'publicPageBuilder.blockTypeServices',
  blockTypeContacts: 'publicPageBuilder.blockTypeContacts', blockTypeMap: 'publicPageBuilder.blockTypeMap',
  blockTypeDivider: 'publicPageBuilder.blockTypeDivider', blockTypeFaq: 'publicPageBuilder.blockTypeFaq',
  items: 'publicPageBuilder.items', removeItem: 'publicPageBuilder.removeItem', addPlatform: 'publicPageBuilder.addPlatform',
  fieldTitle: 'publicPageBuilder.fieldTitle', fieldSubtitle: 'publicPageBuilder.fieldSubtitle',
  fieldBody: 'publicPageBuilder.fieldBody', fieldDescription: 'publicPageBuilder.fieldDescription',
  fieldLabel: 'publicPageBuilder.fieldLabel', fieldUrl: 'publicPageBuilder.fieldUrl',
  fieldImageUrl: 'publicPageBuilder.fieldImageUrl', fieldCtaLabel: 'publicPageBuilder.fieldCtaLabel',
  fieldAddress: 'publicPageBuilder.fieldAddress', fieldPrice: 'publicPageBuilder.fieldPrice',
  fieldPlatform: 'publicPageBuilder.fieldPlatform', fieldValue: 'publicPageBuilder.fieldValue',
  fieldAction: 'publicPageBuilder.fieldAction', fieldPhone: 'publicPageBuilder.fieldPhone', fieldEmail: 'publicPageBuilder.fieldEmail',
  actionUrl: 'publicPageBuilder.actionUrl', actionPhone: 'publicPageBuilder.actionPhone',
  actionEmail: 'publicPageBuilder.actionEmail', actionMessenger: 'publicPageBuilder.actionMessenger',
  messagingApps: 'publicPageBuilder.messagingApps', socialNetworks: 'publicPageBuilder.socialNetworks',
  platformFacebookMessenger: 'publicPageBuilder.platformFacebookMessenger', platformVk: 'publicPageBuilder.platformVk',
  platformInstagram: 'publicPageBuilder.platformInstagram', platformTelegram: 'publicPageBuilder.platformTelegram',
  platformWhatsapp: 'publicPageBuilder.platformWhatsapp', platformViber: 'publicPageBuilder.platformViber',
  platformFacebook: 'publicPageBuilder.platformFacebook', platformThreads: 'publicPageBuilder.platformThreads', platformTiktok: 'publicPageBuilder.platformTiktok',
  tabContent: 'publicPageBuilder.tabContent', tabSettings: 'publicPageBuilder.tabSettings', tabSection: 'publicPageBuilder.tabSection',
  fieldLayout: 'publicPageBuilder.fieldLayout', avatarLayoutCentered: 'publicPageBuilder.avatarLayoutCentered',
  avatarLayoutImageLeft: 'publicPageBuilder.avatarLayoutImageLeft', avatarLayoutImageRight: 'publicPageBuilder.avatarLayoutImageRight',
  avatarLayoutCompact: 'publicPageBuilder.avatarLayoutCompact', paddingTop: 'publicPageBuilder.paddingTop',
  paddingBottom: 'publicPageBuilder.paddingBottom', horizontalMargin: 'publicPageBuilder.horizontalMargin',
  borderRadius: 'publicPageBuilder.borderRadius', borderWidth: 'publicPageBuilder.borderWidth', borderColor: 'publicPageBuilder.borderColor',
  drag: 'publicPageBuilder.drag', resizeSection: 'publicPageBuilder.resizeSection', dropBlock: 'publicPageBuilder.dropBlock', dropSection: 'publicPageBuilder.dropSection',
  clearSelection: 'publicPageBuilder.clearSelection', sectionOff: 'publicPageBuilder.sectionOff', newSection: 'publicPageBuilder.newSection',
  sectionsFromDesign: 'publicPageBuilder.sectionsFromDesign', primarySection: 'publicPageBuilder.primarySection', secondarySection: 'publicPageBuilder.secondarySection',
  none: 'publicPageBuilder.none', buttonIcon: 'publicPageBuilder.buttonIcon', buttonIconLink: 'publicPageBuilder.buttonIconLink',
  buttonIconPhone: 'publicPageBuilder.buttonIconPhone', buttonIconEmail: 'publicPageBuilder.buttonIconEmail', buttonIconMessage: 'publicPageBuilder.buttonIconMessage',
  buttonColor: 'publicPageBuilder.buttonColor', buttonTextColor: 'publicPageBuilder.buttonTextColor',
  shadow: 'publicPageBuilder.shadow', mobileVisible: 'publicPageBuilder.mobileVisible', sectionWidth: 'publicPageBuilder.sectionWidth',
  widthFull: 'publicPageBuilder.widthFull', widthContained: 'publicPageBuilder.widthContained',
  sectionBackground: 'publicPageBuilder.sectionBackground',
  headingStyle: 'publicPageBuilder.headingStyle', bodyStyle: 'publicPageBuilder.bodyStyle', linksStyle: 'publicPageBuilder.linksStyle',
  fontFamily: 'publicPageBuilder.fontFamily', fontSize: 'publicPageBuilder.fontSize', fontWeight: 'publicPageBuilder.fontWeight', fontStyle: 'publicPageBuilder.fontStyle',
  normal: 'publicPageBuilder.normal', italic: 'publicPageBuilder.italic', inherit: 'publicPageBuilder.inherit',
  titleStyle: 'publicPageBuilder.titleStyle', subtitleStyle: 'publicPageBuilder.subtitleStyle', backgroundOpacity: 'publicPageBuilder.backgroundOpacity',
  image: 'publicPageBuilder.image', addImage: 'publicPageBuilder.addImage',
} as const satisfies Record<string, TranslationKey>;

export type PublicPageUiKey = keyof typeof keys;

export function publicPageText(locale: Locale, key: PublicPageUiKey): string {
  const dictionaryKey = keys[key].slice('publicPageBuilder.'.length) as keyof typeof dictionaries.en.publicPageBuilder;
  return dictionaries[locale].publicPageBuilder[dictionaryKey];
}
