import type { NotificationChannel } from '../shared/types/api';

export type SettingsCardCopy = {
  systemTab: string;
  accountTab: string;
  userTab: string;
  specialistPolicyTab: string;
  notificationsTab: string;
  systemTitle: string;
  accountTitle: string;
  userTitle: string;
  timezone: string;
  locale: string;
  firstName: string;
  lastName: string;
  phone: string;
  telegram: string;
  defaultMeetingDuration: string;
  dailyDigestEnabled: string;
  weekStartsOnMonday: string;
  refreshTokenTtlDays: string;
  accessTokenTtlSeconds: string;
  sessionCookieName: string;
  saveSettings: string;
  integrationsTitle: string;
  integrationsSubtitle: string;
  connectGoogle: string;
  connectingGoogle: string;
  disconnectGoogle: string;
  disconnectingGoogle: string;
  telegramBotToken: string;
  telegramBotConnected: string;
  telegramBotNotConnected: string;
  clearTelegramBotToken: string;
  specialistPolicyTitle: string;
  cancelGracePeriodHours: string;
  refundOnLateCancel: string;
  autoCancelUnpaidEnabled: string;
  unpaidAutoCancelAfterHours: string;
  notificationSettingsTitle: string;
  reminderChannelsLabel: string;
  appointmentReminderTimingsLabel: string;
  paymentReminderTimingsLabel: string;
  disabledOption: string;
  channels: Record<NotificationChannel, string>;
};
