const typographyOverride = {
  fontFamily: null,
  fontSize: null,
  fontWeight: null,
  fontStyle: null,
  color: null,
};

const typographyToken = (fontSize: number, fontWeight: number) => ({
  fontFamily: 'Inter, system-ui, sans-serif',
  fontSize,
  fontWeight,
  lineHeight: 1.4,
  letterSpacing: 0,
});

export const validPublicPageDocument = {
  schemaVersion: 4 as const,
  timezone: 'UTC',
  archivedBlocks: [],
  id: 'page-1',
  slug: 'valid-page',
  status: 'draft' as const,
  profile: {
    displayName: 'Name', description: '', logoMediaId: null, avatarMediaId: null,
    avatarPosition: '50% 50%',
  },
  theme: {
    id: 'minimal',
    name: 'Minimal',
    swatches: ['#fff', '#00f', '#fff', '#111'] as const,
    colors: { background: '#fff', surface: '#fff', text: '#111', primary: '#00f' },
    tokens: {
      colors: {
        contrast: '#fff', linkTitle: '#fff', linkSubtitle: '#fff', linkShadow: '#0003',
        linkBorder: '#00f', focus: '#00f', checkboxBackground: '#00f',
      },
      typography: {
        fontFamily: 'Inter, system-ui, sans-serif',
        fontWeight: 400,
        boldFontWeight: 700,
        headingColor: '#111',
        avatarTitle: typographyToken(24, 700),
        avatarBio: typographyToken(16, 400),
        linkTitle: typographyToken(16, 600),
        linkSubtitle: typographyToken(14, 400),
        h1: typographyToken(48, 700),
        h2: typographyToken(32, 700),
        h3: typographyToken(24, 700),
        textLarge: typographyToken(20, 400),
        textMedium: typographyToken(16, 400),
        textSmall: typographyToken(14, 400),
      },
      layout: { blockRadius: 24, linkRadius: 24, linkGap: 10 },
    },
    fontFamily: 'Inter, system-ui, sans-serif',
    roundingStyle: 'rounded' as const,
    backgroundMediaId: null,
    backgroundPreset: null,
    backgroundFit: 'cover' as const,
    backgroundPosition: '50% 50%',
    linkStylePreset: 'primary-fill' as const,
    styleDefaults: {
      sectionBorderRadius: 0,
      blockBorderRadius: 24,
      headingStyle: {
        fontFamily: 'Inter, system-ui, sans-serif', fontSize: 32, fontWeight: 700,
        fontStyle: 'normal' as const, color: '#111',
      },
      textStyle: {
        fontFamily: 'Inter, system-ui, sans-serif', fontSize: 16, fontWeight: 400,
        fontStyle: 'normal' as const, color: '#111',
      },
      linkStyle: {
        titleStyle: {
          fontFamily: 'Inter, system-ui, sans-serif', fontSize: 16, fontWeight: 600,
          fontStyle: 'normal' as const, color: '#fff',
        },
        subtitleStyle: {
          fontFamily: 'Inter, system-ui, sans-serif', fontSize: 14, fontWeight: 400,
          fontStyle: 'normal' as const, color: '#fff',
        },
        backgroundColor: '#00f', backgroundOpacity: 1, borderWidth: 0,
        borderColor: '#00f', shadow: false,
      },
    },
  },
  sections: [{
    id: 'section-1',
    name: '',
    visible: true,
    layout: 'single' as const,
    blocks: [{
      id: 'block-1',
      type: 'text',
      name: '',
      visible: true,
      schedule: { period: null, weekdays: null },
      content: {
        document: {
          type: 'rich-text-v1' as const,
          paragraphs: [{
            size: 'medium' as const,
            fontFamily: null,
            alignment: 'left' as const,
            runs: [{ text: 'Welcome' }],
          }],
        },
      },
      design: {
        linkStyle: null, animation: 'none' as const,
        backgroundColor: null, textColor: null, backgroundMediaId: null, backgroundOverlay: 0,
        backgroundFit: 'cover' as const, backgroundPosition: '50% 50%', paddingTop: 0,
        paddingBottom: 0, borderRadius: null,
      },
    }],
    design: {
      variant: 'custom' as const,
      backgroundColor: null,
      textColor: null,
      backgroundMediaId: null,
      backgroundOverlay: 0,
      backgroundFit: 'cover' as const,
      backgroundPosition: '50% 50%',
      paddingTop: 0,
      paddingBottom: 0,
      horizontalMargin: false,
      borderRadius: null,
      borderWidth: 0,
      borderColor: null,
      shadow: false,
      width: 'full' as const,
      mobileVisible: true,
      headingStyle: typographyOverride,
      textStyle: typographyOverride,
      linkStyle: {
        titleStyle: typographyOverride,
        subtitleStyle: typographyOverride,
        backgroundColor: null,
        backgroundOpacity: null,
        borderWidth: null,
        borderColor: null,
        shadow: null,
      },
    },
  }],
  seo: { title: 'Title', description: 'Description', imageMediaId: null },
  media: [],
  createdAt: '2026-07-28T00:00:00.000Z',
  updatedAt: '2026-07-28T00:00:00.000Z',
};
